### ISSUE TITLE
Upgrade to latest Sinatra

### ISSUE THREAD

**Issue by zepplock** [heroku/addon-template#6]
There's a deprecation method in Sinatra 

```
Thread.exclusive is deprecated, use Mutex
web.1  | /Users/.../.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
web.1  | /Users/.../.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
```

**Comment by djcp** [comment]
Should be resolved by #8
